services:
  person-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: person-tracker
    image: person-tracker:latest
    
    network_mode: host
    
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
    
    volumes:
      - ./models:/app/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./person_tracker.py:/app/person_tracker.py:ro
      - ./model_downloader.py:/app/model_downloader.py:ro
    
    devices:
      - /dev/video0:/dev/video0
    
    group_add:
      - video
    
    command: python person_tracker.py lite
    restart: unless-stopped
    
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
